const types = {
  ADD_TODO: 'ADD_TODO',
  EDIT_TODO: 'EDIT_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  CHANGE_SCREEN: 'CHANGE_SCREEN',
  FETCH_TODOS: 'FETCH_TODOS',
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
  SHOW_ERROR: 'SHOW_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export default types;
